src/MyAbilityFirst/Controllers/ClientController.cs
using AutoMapper;
using MyAbilityFirst.Domain;
using MyAbilityFirst.Domain.ClientFunctions;
using MyAbilityFirst.Models;
using MyAbilityFirst.Services.ClientFunctions;
using MyAbilityFirst.Services.Common;
using NWebsec.Mvc.HttpHeaders.Csp;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyAbilityFirst.Controllers
{
	[Authorize(Roles = "Client")]
	public class ClientController : Controller
	{

		#region Fields

		private readonly IMapper _mapper;
		private readonly IClientService _clientServices;
		private readonly IPresentationService _categoryServices;
		private readonly IUploadService _uploadServices;
		#endregion

		#region Ctor

		public ClientController(IMapper mapper, IClientService clientServices, IPresentationService categoryServices, IUploadService uploadServices)
		{
			this._mapper = mapper;
			this._clientServices = clientServices;
			this._categoryServices = categoryServices;
			this._uploadServices = uploadServices;
		}

		#endregion

		#region Actions

		[HttpGet, Route("client/profile/edit")]
		public ActionResult EditProfile()
		{
			ClientDetailsViewModel vm = mapClientToVM();
			return View(vm);
		}

		[HttpPost, Route("client/profile/edit")]
		[ValidateAntiForgeryToken]
		public ActionResult EditProfile(ClientDetailsViewModel vm)
		{
			if (ModelState.IsValid)
			{
				Client updatedClient = mapVMToClient(vm);
				_clientServices.UpdateClient(updatedClient);

				_clientServices.ReplaceAllUserSubCategories(updatedClient.ID, vm.PostedSubCategoryIDs, new List<UserSubcategory>());
			}
			return RedirectToAction("MyAccount/");
		}

		[HttpGet, Route("client/myaccount")]
		public ActionResult MyAccount()
		{
			ClientDetailsViewModel vm = mapClientToVM();
			return View(vm);
		}

		#endregion

		#region Actions-bookings

		[HttpGet, Route("client/booking/new")]
		public ActionResult NewBooking()
		{
			var client = this.GetLoggedInUser() as Client;

			var vm = new NewBookingViewModel
			{
				Shortlist = this._clientServices.GetShortlist(client.ID)
																				.Select(s => new SelectListItem
																				{
																					Value = s.CareWorkerID.ToString(),
																					Text = s.CareWorkerFirstName
																				}),
				Start = DateTime.Today,
				End = DateTime.Today.AddDays(1)
			};

			return View("Booking/Create", vm);
		}

		[HttpPost, Route("client/booking/new")]
		public ActionResult NewBooking(NewBookingViewModel vm)
		{
			if (ModelState.IsValid)
			{
				var client = this.GetLoggedInUser();
				var clientID = client.ID;
				var careWorkerID = vm.CareWorkerID;
		//		var schedule = new Schedule(vm.Start, vm.End);
				var message = vm.Message;
				//			var booking = this._clientServices.CreateNewBooking(clientID, careWorkerID, schedule, message);

				//			return RedirectToAction("Booking", new { bookingID = booking.ID });
				return null;
			}

			return View("Booking/Create", vm);
		}

		[HttpGet, Route("client/booking/edit/{bookingID:int}")]
		public ActionResult EditBooking(int bookingID)
		{
			var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
			var booking = client.GetBooking(bookingID);
			if (booking == null)
				return View("Error");

			var vm = _mapper.Map<Booking, UpdateBookingViewModel>(booking);
			return View("Booking/Edit", vm);
		}

		[HttpPost, Route("client/booking/edit/{bookingID:int}")]
		[ValidateAntiForgeryToken]
		public ActionResult EditBooking(UpdateBookingViewModel vm)
		{
			if (ModelState.IsValid)
			{
				var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
				var booking = client.GetBooking(vm.BookingID);
				if (booking != null)
					this._clientServices.UpdateBooking(client.ID, vm);

				return RedirectToAction("Booking", new { vm.BookingID });
			}

			return View("Booking/Edit", vm);
		}

		[HttpGet, Route("client/booking/cancel/{bookingID:int}")]
		public ActionResult CancelBooking(int bookingID)
		{
			var client = this.GetLoggedInUser();
			this._clientServices.CancelBooking(client.ID, bookingID);

			return RedirectToAction("BookingHistory");
		}

		[HttpGet, Route("client/booking/complete/{bookingID:int}")]
		public ActionResult CompleteBooking(int bookingID)
		{
			var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
			var booking = client.GetBooking(bookingID);
			if (booking == null)
				return View("Error");

			this._clientServices.CompleteBooking(client.ID, bookingID);
			// here for rating
			return RedirectToAction("Rating", new { bookingID });
		}

		[HttpGet, Route("client/booking/{bookingID:int}")]
		public ActionResult Booking(int bookingId, int? page)
		{
			var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
			var booking = client.GetBooking(bookingId);
			if (booking == null)
				return View("Error");

			ViewBag.UserId = client.ID;
			var bookingVM = this._clientServices.GetBookingViewModel(booking.ID, client.ID);

			int pageIndex = 1;
			int pageSize = 10;
			int pageNumber = (page ?? 1);
			pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

			ViewBag.Notes = bookingVM.CaseNotes.ToPagedList(pageNumber, pageSize);

			return View(bookingVM);
		}

		[HttpPost, Route("client/booking/{bookingID:int}")]
		public ActionResult Booking(UpdateBookingViewModel vm)
		{
			var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
			var booking = client.GetBooking(vm.BookingID);
			if (booking != null && !string.IsNullOrEmpty(vm.Note.Trim()))
				this._clientServices.UpdateBooking(client.ID, vm);

			return RedirectToAction("Booking", new { vm.BookingID });
		}

		[HttpGet]
		public ActionResult BookingHistory(int? page)
		{
			var client = this.GetLoggedInUser();
			var bookings = this._clientServices.GetListOfBookingsViewModel(client.ID);

			int pageIndex = 1;
			int pageSize = 10;
			int pageNumber = (page ?? 1);
			pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
			return View(bookings.ToPagedList(pageNumber, pageSize));
		}

		[HttpGet, Route("client/previousbooking/{bookingID:int}")]
		public ActionResult PreviousBooking(int bookingID)
		{
			var client = this.GetLoggedInUser() as Client;
			var booking = client.GetBooking(bookingID);
			if (booking == null)
				return View("Error");

			ViewBag.UserId = client.ID;
			var bookingVM = this._clientServices.GetBookingViewModel(booking.ID, client.ID);
			return View(bookingVM);
		}

		#endregion

		#region Actions-rating

		[HttpGet]
		public ActionResult Rating(int bookingID)
		{
			var vm = new RatingViewModel();
			return View(vm);
		}

		[HttpPost]
		public ActionResult Rating(RatingViewModel vm)
		{
			var client = this.GetLoggedInUser();
			this._clientServices.AddRating(client.ID, vm);
			return RedirectToAction("RatingDetails", new { vm.BookingID });
		}

		[HttpGet]
		public ActionResult UpdateRating(int bookingID)
		{
			var client = this.GetLoggedInUser();
			var vm = this._clientServices.GetRatingVM(client.ID, bookingID);
			vm.OldOverallScore = vm.OverallScore;
			return View(vm);
		}

		[HttpPost]
		public ActionResult UpdateRating(RatingViewModel vm)
		{
			var client = this.GetLoggedInUser();
			this._clientServices.UpdateRating(client.ID, vm.OldOverallScore, vm);
			return RedirectToAction("RatingDetails", new { vm.BookingID });
		}

		[HttpGet]
		public ActionResult RatingDetails(int bookingID)
		{
			var client = this.GetLoggedInUser();
			var vm = this._clientServices.GetRatingVM(client.ID, bookingID);
			return View(vm);
		}

		#endregion

		#region Actions-uploadfile

		//upload file to Azure storage blob
		[HttpPost]
		public virtual ActionResult UploadFileToAzure()
		{
			string path = ConfigurationManager.AppSettings["uploadAzurePath_Careworker"];
			HttpPostedFileBase file = Request.Files[0];
			string url = this._uploadServices.UploadToAzureStorage(file, path);
			return attachmentProcess(url);
		}

		[HttpDelete]
		public virtual ActionResult DeleteFileFromAzure(string fileName)
		{
			string path = ConfigurationManager.AppSettings["uploadAzurePath_Careworker"];
			if (this._uploadServices.DeleteFromAzureStorage(fileName, path))
				return Json(new { message = "The file has delete !" }, "text/html");
			else
				return Json(new { message = "Error" }, "text/html");
		}

		#endregion

		#region Helpers

		private ClientDetailsViewModel mapClientToVM()
		{
			ClientDetailsViewModel vm = new ClientDetailsViewModel();
			var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
			return _mapper.Map<Client, ClientDetailsViewModel>(client);
		}

		private Client mapVMToClient(ClientDetailsViewModel vm)
		{
			return _mapper.Map(vm, (Client)this.GetLoggedInUser());
		}

		private JsonResult attachmentProcess(string url)
		{
			bool isUploaded = false;
			if (url != null)
			{
				isUploaded = true;
				string message = "100% complete";

				return Json(new
				{
					statusCode = 200,
					status = "File uploaded.",
					file = url,
					isUploaded = isUploaded,
					message = message
				}, "text/html");

			}
			else
			{
				string message = "Error";
				return Json(new
				{
					statusCode = 500,
					status = "Error uploading image.",
					file = string.Empty,
					isUploaded = isUploaded,
					message = message
				}, "text/html");
			}
		}

		#endregion

	}
}

src/MyAbilityFirst/Controllers/MyAccountController.cs
using AutoMapper;
using MyAbilityFirst.Domain;
using MyAbilityFirst.Models;
using MyAbilityFirst.Services.ClientFunctions;
using MyAbilityFirst.Services.Common;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace MyAbilityFirst.Controllers
{
	[Authorize]
	public class MyAccountController : Controller
	{
		#region Fields

		private readonly IUserService _userServices;
		private readonly IClientService _clientServices;
		private readonly IMapper _mapper;

		#endregion

		#region Ctor

		public MyAccountController()
		{

		}

		public MyAccountController(IUserService userService, IClientService clientServices, IMapper mapper)
		{
			this._userServices = userService;
			this._clientServices = clientServices;
			this._mapper = mapper;
		}

		#endregion

		#region Actions

		// GET: MyAccount
		public ActionResult Index()
		{
			string userType = _userServices.GetLoggedInUserType();
			if (userType == "Admin")
			{
				return RedirectToAction("Info", "Manage", new { usertype = userType });
			}
			else
			{
				if (this.GetLoggedInUser().Status == UserStatus.Registered)
				{ // first time login, should redirect to edit profile
					return RedirectToAction("EditProfile", userType, new { usertype = userType });
				}
				else
				{
					return RedirectToAction("MyAccount", userType, new { usertype = userType });
				}
			}
		}

		// GET: MyAccount/Details/5
		[Authorize(Roles = "Admin")]
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			User user = this._userServices.GetUser((int)id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		[Authorize]
		[AcceptVerbs(HttpVerbs.Get|HttpVerbs.Post)]
		public ActionResult _MyAccountSidebar()
		{
			var user = this.GetLoggedInUser();
			string loginID = user.LoginIdentityId;
			string userType = _userServices.GetLoggedInUserType();

			MyAccountViewModel vm = new MyAccountViewModel();
			vm.UserType = userType;
			vm.EmailVerified = _userServices.EmailVerified(loginID);

			if (userType == "Client")
			{
				var client = _clientServices.RetrieveClient(this.GetLoggedInUser().ID);
				vm.Bookings = client.GetBookings();
				vm.PatientList = _clientServices.RetrieveAllPatients(client.ID);
			}
			else if (userType == "CareWorker") 
			{
				
			}

			vm.NavSection = string.Format("{0}-{1}", this.ControllerContext.ParentActionViewContext.RouteData.Values["controller"].ToString(), this.ControllerContext.ParentActionViewContext.RouteData.Values["action"].ToString());
			return PartialView("_MyAccountSidebar", vm);
		}

		[AllowAnonymous]
		[AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
		public ActionResult _MyAccountTopbar()
		{
			MyAccountViewModel vm = new MyAccountViewModel();
			if (Request.IsAuthenticated)
			{
				var thisUser = this.GetLoggedInUser();
				if (thisUser != null)
				{ 
					vm.UserName = _userServices.GetUserFirstLastName(thisUser.ID);
				vm.Shortlists = _userServices.RetrieveAllShortlists(thisUser.ID).Where(s => s.Selected).Select(
					sl => {
						ShortlistViewModel vm1 = new ShortlistViewModel();
						var user = _userServices.GetUser(sl.SelectedUserID);
						vm1 = _mapper.Map(user, vm1);
						return vm1;
					}
				).ToList();
				vm.Notifications = _mapper.Map(_userServices.RetrieveOpenNotifications<Notification>(thisUser.ID).ToList().OrderBy(n => n.NotifiedDate), vm.Notifications);
			}
			}
			return PartialView(vm);
		}

		#endregion
	}
}

src/MyAbilityFirst/Controllers/ProfileController.cs
using AutoMapper;
using MyAbilityFirst.Domain;
using MyAbilityFirst.Models;
using MyAbilityFirst.Services.CareWorkerFunctions;
using System;
using System.Web.Mvc;

namespace MyAbilityFirst.Controllers
{
	[Authorize]
	public class ProfileController : Controller
	{
		private readonly ICareWorkerService _careWorkerServices;
		private readonly IMapper _mapper;

		public ProfileController(ICareWorkerService careWorkerServices, IMapper mapper)
		{
			_careWorkerServices = careWorkerServices;
			_mapper = mapper;
		}
		
		[HttpGet]
		public ActionResult PublicProfile(int id)
		{
			CareWorkerPublicProfileViewModel vm = new CareWorkerPublicProfileViewModel();
			CareWorker careworker = _careWorkerServices.RetrieveCareWorker(id);

			if (careworker != null && careworker.Status == UserStatus.Active)
			{
				vm = _mapper.Map(careworker, vm);
				vm.CareWorkerID = id;
				vm.OverallRating = Math.Round(careworker.TotalRating / careworker.RatingCount, 1);
				return View(vm);
			}
			else
			{
				return RedirectToAction("Index", "Home");
			}
		}

		[Authorize(Roles = "Coordinator")]
		[HttpGet, Route("profile/careworkerprofile/{CareWorkerID:int}")]
		public ActionResult CareWorkerProfile(int careWorkerID)
		{
			CareWorkerDetailsViewModel vm = new CareWorkerDetailsViewModel();
			CareWorker careworker = _careWorkerServices.RetrieveCareWorker(careWorkerID);
			vm = _mapper.Map(careworker, vm);
			return View(vm);
		}
	}
}

src/MyAbilityFirst/Views/Client/Booking.cshtml
@model MyAbilityFirst.Domain.ClientFunctions.UpdateBookingViewModel
@{
	ViewBag.Title = "Booking";
}
<link href="~/Content/bootstrap-rating.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-rating/bootstrap-rating.min.js"></script>
<div class="navbar-left">
	@Html.Action("_MyAccountSidebar", "MyAccount")
</div>

<div class="main-content-wrapper col-md-12">
	<div class="row">

		<h2>Booking details</h2>
		<div class="card card-solid">
			<dl class="dl-horizontal">
				<dt>Carer Name</dt>
				<dd>
					@Model.CareWorkerFirstName  <span class="glyphicon glyphicon-map-marker" style="color:green"></span> @Model.Distance
				</dd>

				<dt>Start - End</dt>
				<dd>
					@Model.Schedule.Duration.Start - @Model.Schedule.Duration.End
				</dd>

				<dt>Message</dt>
				<dd>
					@Html.Raw(Html.Encode(Model.Message).Replace("\n", "<br />"))
				</dd>
				<dt>
					Status
				</dt>
				<dd>
					@{
						@Html.Partial("_BookingStatus", Model.Status)
						if (Model.Status.ToString() == "Requested")
						{
						@Model.Status.ToString() <span> - Waiting carer respond!</span>
						}
						if (Model.Status.ToString() == "Completed")
						{
						<span style="font-size:medium; color:orange">
							@{
								if (Model.Rating.SingleOrDefault() != null)
								{
								<span>&nbsp;&nbsp;</span>
									Double rating = Convert.ToDouble(Model.Rating.SingleOrDefault().OverallScore);
									@Html.BootstrapRating().Value(rating).ReadOnly
									<span> </span>
									@Html.ActionLink("Update", "UpdateRating", "Client", new { bookingId = Model.BookingID }, new { @class = "btn btn-defaut btn-sm", @title = "Rating details" })

								}
							}
						</span>
								}
					}
				</dd>

				<dt></dt>
				<dd>
					@if (Model.Status.ToString() == "Requested")
					{
					@Html.ActionLink("Edit", "EditBooking", "Client", new { bookingID = Model.BookingID }, new { @class = "btn btn-primary btn-sm", @title = "Edit this booking" })
					}
					else if (Model.Status.ToString() == "Accepted")
					{
					@Html.ActionLink("Mark booking as completed", "CompleteBooking", new { bookingId = Model.BookingID }, new { @class = "btn btn-primary btn-sm", @title = "Mark as complete and rate!" })
					}
					else if (Model.Status.ToString() == "Rejected")
					{
					@Html.ActionLink("Cancel this booking", "CancelBooking", new { bookingId = Model.BookingID }, new { @class = "btn btn-primary btn-sm", @title = "Cancel this booking!" })
					}
				</dd>
			</dl>

			<hr />

			<div>
				<dl>
					<dt>
						<span class="label" style="font-size: 12px; color:cadetblue; background-color:blanchedalmond">
							&nbsp; <b>Booking #@Model.BookingID Notes </b>
						</span>
						@if (Model.PreviousBookingID != 0)
						{
						<span>&nbsp; &nbsp;</span>
						<span class="glyphicon glyphicon-hand-right" style="color:orange;word-spacing: -10px;">
							<a href="javascript:window.open('../../PreviousBooking/'+@Model.PreviousBookingID,'popup','top=10,left=300,width=760,height=500,location=no')">Previous Notes</a>
						</span>
						}
					</dt>

					<dd>
						<div class="alert alert-warning" role="alert" style="overflow:auto; max-height:200px">

							@foreach (var item in Model.CaseNotes)
							{
								if (ViewBag.UserId == item.OwnerUserID)
								{
								<span style="color:darkseagreen"><b>Me:</b> @item.Note.ToString() (@item.CreatedAt)</span>
								}
								else if (Model.CareWorkerID == item.OwnerUserID)
								{
								<span style="color:chocolate"><b>Carer:</b> @item.Note.ToString() (@item.CreatedAt)</span>
								}
								else
								{
								<span style="color:lightskyblue"><b>* </b> @item.Note.ToString() (@item.CreatedAt)<b> *</b></span>
								}
								<br />
							}
							<br />
						</div>
					</dd>
				</dl>
			</div>

			@{
				if (Model.Status.ToString() != "Completed" && Model.Status.ToString() != "Cancelled" && Model.Status.ToString() != "Pending" && Model.Status.ToString() != "Reassigned")
				{
					using (Html.BeginForm("Booking", "Client", FormMethod.Post, new { enctype = "multipart/form-data" }))
					{
					@Html.AntiForgeryToken()
						@Html.HiddenFor(model => model.BookingID)
						@Html.HiddenFor(model => model.OwnerUserID)
						@Html.HiddenFor(model => model.Start)
						@Html.HiddenFor(model => model.End)
						@Html.HiddenFor(model => model.Message)
						<div class="form-horizontal">
							<div class="form-group">

								<div class="col-md-12">
									@Html.TextAreaFor(model => model.Note, new { @class = "form-control", @rows = "2", @placeholder = "Write message here and send to carer", @required = "required" })
									@Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
								</div>
							</div>

							<div class="form-group">
								<div class="col-md-12">
									<input type="submit" value="Send" class="btn btn-primary" />
								</div>
							</div>

						</div>
					}
				}
			}
		</div>


	</div>
</div>

src/MyAbilityFirst/Views/Client/BookingHistory.cshtml
@model PagedList.IPagedList<MyAbilityFirst.Domain.ClientFunctions.UpdateBookingViewModel>
@using PagedList.Mvc;
<link href="~/Content/bootstrap-rating.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-rating/bootstrap-rating.min.js"></script>
@{
	ViewBag.Title = "Booking History";
}
<div class="navbar-left">
	@Html.Action("_MyAccountSidebar", "MyAccount")
</div>

<div class="main-content-wrapper">
	<div class="row">
		<div class="col-md-12">
			<h2>Booking History</h2>
			<div class="card card-solid">
				<table class="table">
					<tr>
						<th>Carer Name</th>
						<th>Start</th>
						<th>End</th>
						<th>Message</th>
						<th>Distance</th>
						<th>Status</th>
						<th>Details</th>
						<th>Rating</th>
					</tr>

					@foreach (var item in Model)
					{
					<tr>
						<td>
							@Html.ActionLink(item.CareWorkerFirstName, "publicprofile", "Profile", new { id = item.CareWorkerID }, null)
						</td>
						<td>
							@Convert.ToDateTime(item.Schedule.Duration.Start).ToString("dd/MMM")
						</td>
						<td>
							@Convert.ToDateTime(item.Schedule.Duration.End).ToString("dd/MMM")
						</td>
						<td>
							@{
								if (item.Message != null)
								{
									if (item.Message.Length > 50)
									{
									@item.Message.Substring(0, 50).ToString() @:<span>...</span>
								  }
									else
									{
									@Html.DisplayFor(modelItem => item.Message)
									}
								}
							}
						</td>
						<td>
							<span class="glyphicon glyphicon-map-marker" style="color:green"></span>
							@{if (decimal.Parse(item.Distance) < 1000)
								{
								@Html.Raw(String.Format("{0:0.0}", decimal.Parse(item.Distance)))
								}
								else
								{
								<span>?</span>
								}
							}
							<span>km</span>
						</td>
						<td>
							@Html.Partial("_BookingStatus", item.Status)
						</td>
						<td>
							@Html.HiddenFor(modelItem => item.BookingID)
							@Html.HiddenFor(modelItem => item.CareWorkerID)

							@Html.ActionLink("Details", "Booking", new { bookingId = item.BookingID }, new { @class = "btn btn-primary btn-xs" })
						</td>
						<td>
							@{
								if (item.Status.ToString() == "Completed")
								{
									if (item.Rating.SingleOrDefault() != null)
									{
										Double rating = Convert.ToDouble(item.Rating.SingleOrDefault().OverallScore);
										<span style="font-size:small; color:orange">
											@Html.BootstrapRating().Value(rating).ReadOnly <br />
										</span>
										if (item.Rating.Single().Status == MyAbilityFirst.Domain.RatingStatus.New || item.Rating.Single().Status == MyAbilityFirst.Domain.RatingStatus.Update)
										{
										@Html.ActionLink("Update", "UpdateRating", "client", new { bookingId = item.BookingID }, new { @class = "btn btn-dafaut btn-xs" })
										}
									}
									else
									{
									@Html.ActionLink("Rating", "Rating", new { bookingId = item.BookingID }, new { @class = "btn btn-dafaut btn-xs" })
									}
								}
							}
						</td>
					</tr>
								}
				</table>
				<br />
				Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
				@Html.PagedListPager(Model, page => Url.Action("BookingHistory", new { page }))
			</div>
		</div>
	</div>
</div>

src/MyAbilityFirst/Views/Client/MyAccount.cshtml
@using MvcCheckBoxList.Model
@model MyAbilityFirst.Models.ClientDetailsViewModel
@{
	ViewBag.Title = "MyAccount";
}

<div class="navbar-left">
	@Html.Action("_MyAccountSidebar", "MyAccount")
</div>
<div class="main-content-wrapper">
	<div class="row">
		<div class="col-md-12">
			<div>
				<h1>
					Profile
					@Html.ActionLink("Edit", "EditProfile", "Client", null, new { @class = "btn btn-primary" })
				</h1>
			</div>
			<div class="card card-solid">
				<h3>Personal detail</h3>
				<hr />
				<dl class="dl-horizontal">
					<dt>
						@Html.DisplayNameFor(model => model.FirstName)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.FirstName)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.LastName)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.LastName)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.DoB)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.DoB)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.Gender)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.Gender)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.Email)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.Email)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.Phone)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.Phone)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.Address)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.Address.FullAddress)
					</dd>
					<dt>
						@Html.DisplayNameFor(model => model.NotificationSettings)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.NotificationSettings)
					</dd>

					<dt>
						@Html.DisplayNameFor(model => model.Disclaimers)
					</dt>
					<dd>
						@Html.DisplayFor(model => model.Disclaimers)
					</dd>
					<dt>
						@Html.Label("How did you hear about us?", htmlAttributes: new { @class = "control-label col-md-2" })
					</dt>
					<dd>
						@Html.CheckBoxListFor(
								model => model.PostedSubCategoryIDs,
								model => model.MarketingInfoList,
								item => item.ID,
								item => item.Name,
								model => model.PreviousMarketingInfo,
								Position.Vertical,
								x => new { disabled = "disabled" })
					</dd>
				</dl>
			</div>
			<div>
				<h1 class="page-header">
					@Html.ActionLink("Edit", "EditProfile", "Client", null, new { @class = "btn btn-default" })
				</h1>
			</div>
		</div>
	</div>
</div>