src/MyAbilityFirst/Controllers/PatientController.cs
using AutoMapper;
using MyAbilityFirst.Domain;
using MyAbilityFirst.Models;
using MyAbilityFirst.Services.ClientFunctions;
using MyAbilityFirst.Services.Common;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;

namespace MyAbilityFirst.Controllers
{
	[Authorize(Roles = "Client")]
	public class PatientController : Controller
	{

		#region Fields

		private readonly IClientService _clientServices;
		private readonly IPresentationService _categoryServices;
		private readonly IMapper _mapper;
		private readonly IUploadService _uploadServices;

		#endregion

		#region Ctor

		public PatientController(IClientService clientServices, IPresentationService categoryServices, IMapper mapper, IUploadService uploadServices)
		{
			this._clientServices = clientServices;
			this._categoryServices = categoryServices;
			this._mapper = mapper;
			this._uploadServices = uploadServices;
		}

		#endregion

		#region Actions

		[HttpGet, Route("patient/new")]
		public ActionResult NewProfile()
		{
			var client = this.GetLoggedInUser();
			PatientDetailsViewModel vm = mapPatientToVM(new Patient(client.ID));
			return View(vm);
		}

		[HttpPost, Route("patient/new")]
		[ValidateAntiForgeryToken]
		public ActionResult NewProfile(PatientDetailsViewModel vm)
		{
			if (ModelState.IsValid)
			{
				var client = this.GetLoggedInUser();
				Patient persistedPatient = _clientServices.CreatePatient(client.ID, mapVMToPatient(vm));
				vm.PatientID = persistedPatient.ID;
				_clientServices.ReplaceAllContacts(client.ID, persistedPatient.ID, vm.Contacts);

				persistCategories(vm);
			}

			return RedirectToAction("MyAccount", "Client");
		}

		[HttpGet, Route("patient/{patientID:int}")]
		public ActionResult EditProfile(int patientID)
		{
			var client = this.GetLoggedInUser();
			Patient currentPatient = _clientServices.RetrievePatient(client.ID, patientID);
			if (currentPatient != null)
			{
				PatientDetailsViewModel vm = mapPatientToVM(currentPatient);
				return View(vm);
			}


			return RedirectToAction("MyAccount", "Client");
		}

		[HttpPost, Route("patient/{patientID:int}")]
		[ValidateAntiForgeryToken]
		public ActionResult EditProfile(PatientDetailsViewModel vm)
		{
			var client = this.GetLoggedInUser();
			Patient currentPatient = _clientServices.RetrievePatient(client.ID, vm.PatientID);
			if (ModelState.IsValid && currentPatient != null)
			{
				Patient persistedPatient = _clientServices.UpdatePatient(client.ID, mapVMToPatient(vm));
				_clientServices.ReplaceAllContacts(client.ID, persistedPatient.ID, vm.Contacts);

				persistCategories(vm);
				return RedirectToAction("MyAccount/" + persistedPatient.ID.ToString());
			}
			return RedirectToAction("MyAccount", "Client");
		}

		[HttpGet, Route("patient/myaccount/{id:int}")]
		public ActionResult MyAccount(int id)
		{
			var client = this.GetLoggedInUser();
			Patient currentPatient = _clientServices.RetrievePatient(client.ID, id);
			if (currentPatient != null)
			{
				PatientDetailsViewModel vm = mapPatientToVM(currentPatient);
				return View(vm);
			}
			return RedirectToAction("MyAccount", "Client");
		}

		[HttpPost]
		public ActionResult NewContact(PatientDetailsViewModel vm)
		{
			Contact newContact = new Contact();
			newContact.PatientID = vm.PatientID;
			vm.Contacts = vm.Contacts ?? new List<Contact>();
			vm.RelationshipDropDownList = _categoryServices.GetSubCategorySelectList("Relationship");
			vm.Contacts.Add(newContact);
			return PartialView("_NewContact", vm);
		}

		[HttpGet, Route("patient/{patientID:int}/attachments/")]
		public ActionResult ManageAttachments(int patientID)
		{
			var client = this.GetLoggedInUser();
			Patient currentPatient = _clientServices.RetrievePatient(client.ID, patientID);
			if (currentPatient != null)
			{
				PatientAttachmentViewModel vm = _mapper.Map<Patient, PatientAttachmentViewModel>(currentPatient);
				ViewBag.PathUpload = Url.Action("Upload", "Attachment");
				ViewBag.PathDelete = Url.Action("Delete", "Attachment");

				return View(vm);
			}

			return RedirectToAction("MyAccount", "Client");
		}

		#endregion

		#region Helper

		private void persistCategories(PatientDetailsViewModel vm)
		{
			_clientServices.ReplaceAllUserSubCategories(vm.PatientID, vm.PostedSubCategoryIDs, new List<UserSubcategory>());
		}

		private PatientDetailsViewModel mapPatientToVM(Patient patient)
		{
			PatientDetailsViewModel vm = new PatientDetailsViewModel();
			vm = _mapper.Map<Patient, PatientDetailsViewModel>(patient);
			return vm;
		}

		private Patient mapVMToPatient(PatientDetailsViewModel vm)
		{
			var client = this.GetLoggedInUser();
			Patient patient = _clientServices.RetrievePatient(client.ID, vm.PatientID);
			vm.ClientID = client.ID;
			return _mapper.Map(vm, patient);
		}

		#endregion

	}
}

src/MyAbilityFirst/Controllers/SearchController.cs
using System.Web.Mvc;
using AutoMapper;
using MyAbilityFirst.Services.SearchFunctions;
using MyAbilityFirst.Models;

namespace MyAbilityFirst.Controllers
{
	[Authorize]
	public class SearchController : Controller
	{

		#region Fields

		private readonly IMapper _mapper;
		private readonly ISearchService _searchServices;

		#endregion

		#region Ctor

		public SearchController(IMapper mapper, ISearchService searchServices)
		{
			this._mapper = mapper;
			this._searchServices = searchServices;
		}

		#endregion

		#region Actions
		[Route("search/SearchCareWorker")]
		public ActionResult SearchCareWorker(SearchViewModel vm)
		{
			if (ModelState.IsValid)
			{
				vm.UserID = this.GetLoggedInUser().ID;
				vm = _mapper.Map(vm, vm);
				if (vm.SearchTerm != null || vm.Longitude != null || vm.Latitude != null || vm.RadiusInKm != null || vm.PostedSubcategoryIDs != null || vm.PostedGenderIDs != null || vm.PostedLanguageIDs != null || vm.PostedCultureIDs != null || vm.PostedReligionIDs != null || vm.PostedPersonalityIDs != null)
				{
					vm.SearchResults = _searchServices.GetCareWorkerSearchResults(
						vm.UserID,
						vm.SearchTerm,
						vm.Longitude,
						vm.Latitude,
						vm.RadiusInKm,
						vm.PostedSubcategoryIDs,
						vm.PostedGenderIDs,
						vm.PostedLanguageIDs,
						vm.PostedCultureIDs,
						vm.PostedReligionIDs,
						vm.PostedPersonalityIDs,
						vm.SortOption,
						vm.PageNumber,
						vm.PageSize
					);
				}
				return View(vm);
			}
			return RedirectToAction("SearchCareWorker");
		}

		[HttpPost]
		public ActionResult SearchCareWorkerPaged(SearchViewModel vm)
		{
			vm.UserID = this.GetLoggedInUser().ID;
			vm.SearchResults = _searchServices.GetCareWorkerSearchResults(
				vm.UserID,
				vm.SearchTerm,
				vm.Longitude,
				vm.Latitude,
				vm.RadiusInKm,
				vm.PostedSubcategoryIDs,
				vm.PostedGenderIDs,
				vm.PostedLanguageIDs,
				vm.PostedCultureIDs,
				vm.PostedReligionIDs,
				vm.PostedPersonalityIDs,
				vm.SortOption,
				vm.PageNumber,
				vm.PageSize
			);
			return PartialView("_SearchResults", vm);
		}

		[HttpGet]
		public JsonResult SearchCareWorkerPagedJson(
			string SearchTerm = "", 
			decimal? Longitude = null,
			decimal? Latitude = null,
			float? radiusInKm = 0, 
			int[] PostedSubcategoryIDs = null,
			int[] PostedGenderIDs = null,
			int[] PostedLanguageIDs = null,
			int[] PostedCultureIDs = null,
			int[] PostedReligionIDs = null,
			int[] PostedPersonalityIDs = null,
			SortOption SortOption = SortOption.Closest,
			int PageNumber = 1,
			int PageSize = PageSize.DefaultSearchPageSize
		)
		{
			var res = Json(
				_searchServices.GetCareWorkerSearchResults(
					this.GetLoggedInUser().ID,
					SearchTerm,
					Longitude,
					Latitude,
					radiusInKm,
					PostedSubcategoryIDs,
					PostedGenderIDs,
					PostedLanguageIDs,
					PostedCultureIDs,
					PostedReligionIDs,
					PostedPersonalityIDs,
					SortOption,
					PageNumber,
					PageSize
				)
			);
			res.ContentEncoding = System.Text.Encoding.UTF8;
			res.ContentType = "application/json";
			res.MaxJsonLength = 100000;
			res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
			res.RecursionLimit = 10;
			return res;
		}
		#endregion

	}

}

src/MyAbilityFirst/Controllers/ShortlistController.cs
using AutoMapper;
using MyAbilityFirst.Domain;
using MyAbilityFirst.Models;
using MyAbilityFirst.Services.Common;
using System.Web.Mvc;

namespace MyAbilityFirst.Controllers
{
	[Authorize]
	public class ShortlistController : Controller
	{

		#region Fields

		private readonly IMapper _mapper;
		private readonly IUserService _userServices;

		#endregion

		#region Ctor

		public ShortlistController(IMapper mapper, IUserService userServices)
		{
			this._mapper = mapper;
			this._userServices = userServices;
		}

		#endregion

		#region Actions

		[HttpGet]
		public ActionResult ShortlistButton(int selectedUserID)
		{
			ShortlistViewModel vm = new ShortlistViewModel();
			var user = this.GetLoggedInUser();
			if (user == null) 
			{
				return PartialView(vm);
			}
			Shortlist shortlist = _userServices.RetrieveShortlistBySelectedUserID(user.ID, selectedUserID);
			vm = _mapper.Map<Shortlist, ShortlistViewModel>(shortlist, vm) ?? new ShortlistViewModel();
			vm.SelectedUserID = shortlist == null ? selectedUserID : shortlist.SelectedUserID;
			return PartialView(vm);
		}


		[HttpPost]
		public ActionResult UpdateShortlist(ShortlistViewModel vm)
		{
			if (ModelState.IsValid)
			{
				int ownerUserID = this.GetLoggedInUser().ID;
				Shortlist shortlist = _userServices.RetrieveShortlistBySelectedUserID(ownerUserID, vm.SelectedUserID);
				if (shortlist == null) 
				{
					return AddShortlist(vm);
				}
				shortlist = _mapper.Map<ShortlistViewModel, Shortlist>(vm, shortlist);
				_userServices.UpdateShortlist(ownerUserID, shortlist);
			}
			return Json(vm);
		}

		[HttpPost]
		public ActionResult AddShortlist(ShortlistViewModel vm)
		{
			if (ModelState.IsValid)
			{
				int ownerUserID = this.GetLoggedInUser().ID;
				Shortlist shortlist = new Shortlist(ownerUserID, vm.SelectedUserID, vm.Selected);
				shortlist = _mapper.Map<ShortlistViewModel, Shortlist>(vm, shortlist);
				_userServices.CreateShortlist(ownerUserID, shortlist);
			}
			return Json(vm);
		}

		#endregion

	}
}

src/MyAbilityFirst/Views/Shared/ShortlistButton.cshtml
@model MyAbilityFirst.Models.ShortlistViewModel

<button id="shortlist-toggle-btn-@Model.SelectedUserID" class="@(Model.Selected ? "btn btn-success btn-xs" : "btn btn-default btn-xs")" data-loading-text="<i class='glyphicon glyphicon-hourglass'></i>" type="button"
				onclick="AJAXPostShortlistButton(
					'@(Url.Action("UpdateShortlist", "Shortlist", Model))', 
					{SelectedUserID: @Model.SelectedUserID , Selected: @Json.Encode(Model.Selected)}, 
					'#shortlist-toggle-btn-@Model.SelectedUserID', 
					'btn-success btn-default',
					[])"
>
	<i class="glyphicon glyphicon-star" id="shortlist-toggle-icon"></i>
</button>

src/MyAbilityFirst/Views/Shared/_BookingStatus.cshtml
@model MyAbilityFirst.Domain.BookingStatus

@switch (@Model.ToString())
{
	case "Accepted":
	<span class="label label-success">@Model.ToString()</span>
		break;
	case "Rejected":
	<span class="label label-danger">@Model.ToString()</span>
		break;
	case "Completed":
	<span class="label label-info">@Model.ToString()</span>
		break;
	case "Cancelled":
	<span class="label label-default">@Model.ToString()</span>
		break;
	case "Requested":
	<span class="label label-warning">New</span>
		break;
	default:
	<span><b> @Model.ToString()</b></span>
		break;
}

src/MyAbilityFirst/Views/Shared/_MyAccountSidebar.cshtml
@model MyAbilityFirst.Models.MyAccountViewModel

@if (!Model.EmailVerified)
{
	<br />
	<div class="alert alert-warning bottom-buffer-10">
		Your email has not been verified. @Html.ActionLink("Click here", "ResendConfirmEmail", "Account") to re-send your confirmation email.
	</div>
	<br />
}

<div>
	<ul class="list-unstyled">
		<li @(Model.NavSection.Contains("Client-") && !Model.NavSection.Contains("Booking") ? "class=active" : "")>
			<h4><span class="fa fa-key"></span> My profile</h4>
			<ul class="list-unstyled">
				<li>@Html.ActionLink("Profile", "EditProfile", Model.UserType, routeValues: null, htmlAttributes: new { title = "My Profile" })</li>
				<li>@Html.ActionLink("Change Password", "changepassword", "Manage", routeValues: null, htmlAttributes: new { title = "Change Password" })</li>
			</ul>
		</li>
	</ul>
	<hr />
	@if (Model.UserType == "Client")
	{
	<ul class="list-unstyled">
		<li @(Model.NavSection.Contains("Patient-") ? "class=active" : "")>
			<h4><span aria-hidden="true" class="fa fa-users"></span> Patient Management</h4>
			<ul class="list-unstyled">
				<li>@Html.ActionLink("Add a patient", "NewProfile", "Patient", routeValues: null, htmlAttributes: new { title = "Add Patient" })</li>
				<li>
					Update a patient
					@if (Model.PatientList.Any())
					{
					<ul>
						@foreach (var item in Model.PatientList)
					{
					<li>@Html.ActionLink(item.FirstName + " " + item.LastName, "EditProfile", "Patient", new { patientID = item.ID }, htmlAttributes: new { title = "MyAccount" })</li>
					}
					</ul>
					}
				</li>
			</ul>
		</li>
	</ul>
	<hr />
	<ul class="list-unstyled">
		<li @(Model.NavSection.Contains("Job-") ? "class=active" : "")>
			<h4><span aria-hidden="true" class="fa fa-heart-o"></span> Job postings</h4>
			<ul class="list-unstyled">
				<li>@Html.ActionLink("Post a new job", "create", "Job", routeValues: null, htmlAttributes: new { title = "Post a Job" })</li>
				<li>@Html.ActionLink("All jobs / Update a job", "index", "Job", routeValues: null, htmlAttributes: new { title = "Update a Job" })</li>
			</ul>
		</li>
	</ul>
	<hr />
		<ul class="list-unstyled">
			<li @(Model.NavSection.Contains("Booking") ? "class=active" : "")>
				<h4><span aria-hidden="true" class="fa fa-tasks"></span> Booking Management</h4>
				<ul class="list-unstyled">
					<li>@Html.ActionLink("Create a new booking", "NewBooking", "Client", routeValues: null, htmlAttributes: new { title = "Post a Job" })</li>
					@{
						var bookings = "";   /// Model.Bookings.Where(a => (int)a.Status != 5 && (int)a.Status != 6);
					}
					@if (bookings.Any())
				{
				<li>
					<ul>
						@foreach (var item in bookings)
						{
						<li>
						@*	@Html.ActionLink(string.Format("Booking #{0}", item.ID.ToString()), "Booking", "Client", new { bookingId = item.ID }, null)

	@Html.Partial("_BookingStatus", item.Status)*@
						</li>

						}
					</ul>
				</li>
				}
				</ul>
				<ul class="list-unstyled">
					<li>@Html.ActionLink("Booking history", "BookingHistory", "Client", routeValues: null, htmlAttributes: new { title = "Post a Job" })</li>
				</ul>
			</li>
		</ul>
			}

	@if (Model.UserType == "CareWorker")
			{
			<h4><span class="fa fa-tasks"></span> Booking Management</h4>
			<ul class="list-unstyled">
				<li>@Html.ActionLink(" My Bookings", "Bookings", "CareWorker", routeValues: null, htmlAttributes: new { title = "My Bookings" })</li>
			</ul>
			}
	<hr />
	<ul class="list-unstyled">

		<li>
			<h4>
				<span aria-hidden="true" class="fa fa-search">
					@Html.ActionLink("Search for CareWorkers", "SearchCareWorker", "Search", routeValues: null, htmlAttributes: new { title = "Search" })
				</span>
		</h4>
		</li>
	</ul>
</div>

src/MyAbilityFirst/Views/Shared/_MyAccountTopbar.cshtml
@model MyAbilityFirst.Models.MyAccountViewModel
@if (Request.IsAuthenticated)
{
	using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
	{
	@Html.AntiForgeryToken()

		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">
					<span class="glyphicon glyphicon-star"></span>
					<sup id="shortlistcounter">@if (Model.Shortlists != null) {@Model.Shortlists.Count(s => s.Selected)}</sup>
				</a>
				<div class="dropdown-menu" role="menu">
					@if (Model.Shortlists != null)
					{
						foreach (var shortlist in Model.Shortlists.Where(s => s.Selected))
						{
						<div class="col-md-12">
							<a href="@Url.Action("PublicProfile", "Profile", new { id = shortlist.SelectedUserID })"> 
								<img src=@shortlist.PictureURL class="media-object img-circle" alt="Sample Image" style="width:60px" title="see profile">
								@shortlist.FirstName @shortlist.LastName 
							</a>
						</div>
						}
					}
				</div>
			</li>
		</ul>

		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">
					<span class="glyphicon glyphicon-envelope"></span>
					<sup id="notificationcounter">@if (Model.Notifications != null && Model.Notifications.Count(n => !n.Read) > 0) {@Model.Notifications.Count(n => !n.Read)}</sup>
				</a>
				<div id="Notifications" class="dropdown-menu notification" role="menu">
					@if (Model.Notifications != null)
					{
						foreach (var notification in Model.Notifications)
						{
							@Html.Partial("~/Views/ChatRoom/_ChatNotification.cshtml", notification)
						}
					}
				</div>
			</li>
		</ul>

		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">
					<span class="glyphicon glyphicon-user"></span>
					@Model.UserName <span aria-hidden="true" class="caret"></span>
				</a>
				<ul class="dropdown-menu" role="menu">
					<li><a href="@Url.Action("Index", "MyAccount")"><span aria-hidden="true" class="fa fa-user"></span> My Account</a></li>
					<li><a href="javascript:document.getElementById('logoutForm').submit()"><span aria-hidden="true" class="fa fa-sign-out"></span> Log off</a></li>
				</ul>
			</li>
		</ul>
	}
}
else
{
		<ul class="nav navbar-nav navbar-right">
			<li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
			<li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
		</ul>
}